# Generated by Django 4.2.6 on 2023-10-11 02:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
