# Generated by Django 4.2.6 on 2023-10-11 09:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("balance", models.PositiveBigIntegerField(default=0)),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "wallet_account",
            },
        ),
        migrations.CreateModel(
            name="WalletUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_xid",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that ID already exists."
                        },
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "wallet_users",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        error_messages={
                            "unique": "A reference with that ID already exists."
                        },
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("action_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.PositiveBigIntegerField(default=0)),
                (
                    "action_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_transactions",
                        to="wallet.walletuser",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.walletaccount",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_transactions",
            },
        ),
        migrations.AddField(
            model_name="walletaccount",
            name="owned_by",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to="wallet.walletuser",
            ),
        ),
    ]
